version: '3.7'

services:
  nginx:
    command: ["nginx", "-c", "/nginx_conf/nginx.conf", "-g", "daemon off;"]
    image: nginx:1.17.5-alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/nginx_conf/nginx.conf
      - ../../public/boschdoc:/usr/share/nginx/html

  # backend:
  #   image: brambdocker/boschdoc-draft
