dev:
  entrypoint: "./entrypoint.sh"
  environment:
    - SSH_AUTH_SOCK=/ssh-agent
  image: gijsjan/webdev:1.1
  ports:
    - "3000:3000"
    - "4000:4000"
  volumes:
    - ..:/home/developer/project
    - ../../hilib:/home/developer/hilib
    - ./tmuxinator.yml:/home/developer/.tmuxinator/project.yml
    - ./entrypoint.sh:/home/developer/entrypoint.sh
    - ~/.vimrc:/home/developer/.vimrc
    - ~/.ssh:/home/developer/.ssh
    - ${SSH_AUTH_SOCK}:/ssh-agent
