# # Usage:
# docker build -t e4fb -f Dockerfile.build .
# docker run -it -v $(pwd):/work e4fb
# edit apps/*/.env to taste
# npm install && ./dist.sh
# # the output is in public/

FROM node:slim
WORKDIR /work
CMD "bash"