name: build-docker-images

on:
  push:
    tags:
      - '*'
      - '**'
  release:
    types: [ published ]
  workflow_dispatch:

env:
  REGISTRY_FQDN: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  WORK_IMAGE_NAME: huygensing/elaborate-frontend
  WORK_IMAGE_FILE: docker/work-environment/Dockerfile
  PUBLICATION_IMAGE_NAME: huygensing/elaborate-publication-frontend
  PUBLICATION_IMAGE_FILE: docker/publication/Dockerfile
  BOSCHDOC_IMAGE_NAME: huygensing/elaborate-boschdoc-frontend
  BOSCHDOC_IMAGE_FILE: docker/boschdoc/Dockerfile

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY_FQDN }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker (work-frontend)
        id: meta-work
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY_FQDN }}/${{ env.WORK_IMAGE_NAME }}

      - name: Build and push Docker image (work-frontend)
        uses: docker/build-push-action@v3.2.0
        with:
          file: ${{ env.WORK_IMAGE_FILE }}
          labels: ${{ steps.meta-work.outputs.labels }}
          tags: ${{ steps.meta-work.outputs.tags }}
          push: true

      - name: Extract metadata (tags, labels) for Docker (publication-frontend)
        id: meta-pub
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY_FQDN }}/${{ env.PUBLICATION_IMAGE_NAME }}

      - name: Build and push Docker image (publication-frontend)
        uses: docker/build-push-action@v3.2.0
        with:
          file: ${{ env.PUBLICATION_IMAGE_FILE }}
          labels: ${{ steps.meta-pub.outputs.labels }}
          tags: ${{ steps.meta-pub.outputs.tags }}
          push: true

      - name: Extract metadata (tags, labels) for Docker (boschdoc-frontend)
        id: meta-boschdoc
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY_FQDN }}/${{ env.BOSCHDOC_IMAGE_NAME }}

      - name: Build and push Docker image (boschdoc-frontend)
        uses: docker/build-push-action@v3.2.0
        with:
          file: ${{ env.BOSCHDOC_IMAGE_FILE }}
          labels: ${{ steps.meta-boschdoc.outputs.labels }}
          tags: ${{ steps.meta-boschdoc.outputs.tags }}
          push: true
